### ISSUE TITLE
Provide Windows builds

### ISSUE THREAD

**Issue by bUbblE1968** [dingusdev/dingusppc#28]
subj

**Comment by dingusdev** [comment]
The emulator is too unfinished at this time. Once we get the emulator at a point where you can use the Mac OS, this will be considered.

**Comment by malespiaut** [comment]
Hello,

I would like to add my support to this issue of being able to download nightly builds.

I use Linux instead of Windows. But I think that it would be nice, even if there are only Windows builds, available for download and run, even if the emulator is very unfinished.

That would also probably help people report bugs. If you are afraid to get overwhelmed by bug reports, and potentially badly formatted bug reports, I highly encourage you to have a GitHub issue template (see https://github.com/ziglang/zig/blob/master/.github/ISSUE_TEMPLATE/bug.yml).

Best regards.

**Comment by dingusdev** [comment]
A release for DingusPPC is now available and a Windows build has been compiled. As for nightly builds, I'm afraid I can't do that at this time. What I'll be doing instead is a new alpha every few months.
